#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CheckListMobile.Resource", IsApplication=true)]

namespace CheckListMobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int redmark = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int Area = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int Area1 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int Area2 = 2131034119;
			
			// aapt resource value: 0x7f05001c
			public const int BtnCheckList = 2131034140;
			
			// aapt resource value: 0x7f050021
			public const int BtnLogin = 2131034145;
			
			// aapt resource value: 0x7f050004
			public const int Cabecalho = 2131034116;
			
			// aapt resource value: 0x7f050018
			public const int Chave = 2131034136;
			
			// aapt resource value: 0x7f05000f
			public const int Combustivel = 2131034127;
			
			// aapt resource value: 0x7f050017
			public const int Documento = 2131034135;
			
			// aapt resource value: 0x7f050012
			public const int Farois = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int Ferramentas = 2131034131;
			
			// aapt resource value: 0x7f050003
			public const int KM = 2131034115;
			
			// aapt resource value: 0x7f050015
			public const int Lanternas = 2131034133;
			
			// aapt resource value: 0x7f05001e
			public const int Livre = 2131034142;
			
			// aapt resource value: 0x7f05001a
			public const int OBS1 = 2131034138;
			
			// aapt resource value: 0x7f05000e
			public const int Oleo = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int P90 = 2131034128;
			
			// aapt resource value: 0x7f050016
			public const int Pintura = 2131034134;
			
			// aapt resource value: 0x7f050014
			public const int Pneu = 2131034132;
			
			// aapt resource value: 0x7f050011
			public const int Retrovisores = 2131034129;
			
			// aapt resource value: 0x7f050020
			public const int Senha = 2131034144;
			
			// aapt resource value: 0x7f050001
			public const int Tatico = 2131034113;
			
			// aapt resource value: 0x7f05001f
			public const int Usuario = 2131034143;
			
			// aapt resource value: 0x7f050009
			public const int VTR = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int VTR1 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int VTR2 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int VTR3 = 2131034124;
			
			// aapt resource value: 0x7f050022
			public const int btnCheck = 2131034146;
			
			// aapt resource value: 0x7f050024
			public const int btnManutencao = 2131034148;
			
			// aapt resource value: 0x7f050023
			public const int btnOleo = 2131034147;
			
			// aapt resource value: 0x7f05001b
			public const int btnPro = 2131034139;
			
			// aapt resource value: 0x7f05001d
			public const int btnProblemas = 2131034141;
			
			// aapt resource value: 0x7f050025
			public const int btnSair = 2131034149;
			
			// aapt resource value: 0x7f05000d
			public const int widget41 = 2131034125;
			
			// aapt resource value: 0x7f050002
			public const int widget411 = 2131034114;
			
			// aapt resource value: 0x7f050019
			public const int widget4111 = 2131034137;
			
			// aapt resource value: 0x7f050008
			public const int widget74 = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int widget76 = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CheckList = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Inicio = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Manutencao = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Oleo = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Principal = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
